 export const data = [
  {
    name: "Kushagra Gupta",
    address: "221B Bakers Street",
    location: "London",
    price: "$2,200",
    moveInDate: "2022-8-11",
    propertyType: "House",
    area: "2200m",
    beds: 4,
    bathrooms: 4,
  },
  {
    name: "Ankit Srivastava",
    address: "230L Lakers Street",
    location: "London",
    price: "$1,500",
    moveInDate: "2022-10-12",
    propertyType: "House",
    area: "4000m",
    beds: 2,
    bathrooms: 1,
  },
  {
    name: "Harsh Mishra",
    address: "11 street ola",
    location: "New York",
    price: "$3,000",
    moveInDate: "2022-11-12",
    propertyType: "House",
    area: "1000m",
    beds: 2,
    bathrooms: 2,
  },
  {
    name: "Ayush Bhardwaj",
    address: "11 a Road",
    location: "New York",
    price: "$2,500",
    moveInDate: "2023-1-12",
    propertyType: "House",
    area: "3000m",
    beds: 3,
    bathrooms: 4,
  },
  {
    name: "Shrey Srivastava",
    address: "230L Lakers Street",
    location: "Mumbai",
    price: "$8,00",
    moveInDate: "2022-9-12",
    propertyType: "Office",
    area: "2000m",
    beds: 1,
    bathrooms: 2,
  },
  {
    name: "Aditya Singh",
    address: "24 Yorkland",
    location: "London",
    price: "$1,1520",
    moveInDate: "2022-11-12",
    propertyType: "Office",
    area: "6000m",
    beds: 2,
    bathrooms: 1,
  },
  {
    name: "Sumael Khan",
    address: "DvC Road",
    location: "New York",
    price: "$8,400",
    moveInDate: "2022-10-12",
    propertyType: "Industry",
    area: "7000m",
    beds: 4,
    bathrooms: 4,
  },
  {
    name: "Rahul Singh",
    address: "23 Palm walks",
    location: "Mumbai",
    price: "$4,000",
    moveInDate: "2022-12-12",
    propertyType: "Industry",
    area: "3000m",
    beds: 1,
    bathrooms: 1,
  },
  {
    name: "Abhishek Awasthi",
    address: "2312 StoneHenge",
    location: "Mumbai",
    price: "$9,90",
    moveInDate: "2023-2-12",
    propertyType: "Industry",
    area: "2000m",
    beds: 5,
    bathrooms: 2,
  },
  {
    name: "Saumya Singh",
    address: "Folk Street Road",
    location: "New York",
    price: "$2,312",
    moveInDate: "2022-11-12",
    propertyType: "Office",
    area: "3000m",
    beds: 3,
    bathrooms: 3,
  },
  {
    name: "Ishaan Maheshwari",
    address: "14 Street Cred",
    location: "Mumbai",
    price: "$5,000",
    moveInDate: "2022-12-12",
    propertyType: "House",
    area: "4000m",
    beds: 7,
    bathrooms: 4,
  },
  {
    name: "Ankit Sharma",
    address: "Street Good",
    location: "New York",
    price: "$1,213",
    moveInDate: "2022-11-12",
    propertyType: "House",
    area: "2000m",
    beds: 1,
    bathrooms: 3,
  },
 
  
];
